### ISSUE TITLE
Use annotation files to run DSC

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc2#49]
This idea popped up during my discussion with Wei earlier today when I try to explain the DSC annotation mechanism. He seems to think running the DSC and annotate it after is counter-intuitive I've convinced him why it makes sense yet we both find it can be useful if we can also give names to DSC sequence we are interested in beforehand so that we can run them exclusively. Need some work though and it will break some existing features but I'll update the doc as I make the changes. I make this proposal  No. 4 on my current TODO list.

**Comment by stephens999** [comment]
I agree with Wei that naming as you run is the natural way to think about
this as a user...

The exception is when you start running all combinations of parameters
rather than just a select group of methods. Then it becomes easier to just
run everything and annotate after.

I am more interested in the former application, where you have to think
hard before running a method rather than running all parameter
combinations. But I think both are of interest.

Matthew

**Comment by gaow** [comment]
Another feature we need when doing this is to allow for combination of logic across parameters. Currently we have:

```
large_sample:
  simulate: 
    N: % N > 100

small_feature:
  simulate:
     P: % P < 10
```

But the concept of large or small here is relative. We should allow for tags such as:

```
small_n_large_p:
   simulate: N < P

large_n_small_p:
   simulate: P < N
```

Still have to give some more thoughts syntax-wise but this is the feature we currently lack.
