### ISSUE TITLE
Create default annotations

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc2#60]
The annotation file below is from `dsc2-regression`. It is a bit dumb because basically I create one tag per executable (with the exception when `Mytune` parameter is involved)

Perhaps a feature to "draft" these annotations is helpful? ie, by default DSC2 will spit an annotation file that gives tags to each executable, as a "template", and users can work from there. 

```
sim1:
  scenarios:
    exec: sim1
    
sim2:
  scenarios:
    exec: sim2
sim3:
  scenarios:
    exec: sim3
    
sim4:
  scenarios:
    exec: sim4

lasso:
  methods:
    exec: lasso.wrapper.R 

elastic_net:
  methods:
    exec: elasticnet.wrapper.R 

naive_elastic_net:
  methods:
    exec: naive.elasticnet.wrapper.R

lasso10fold:
  methods:
    exec: lasso.cv.wrapper.R
    Mytune: 10

elastic_net10fold:
  methods:
    exec: elasticnet.cv.wrapper.R
    Mytune: 10

naive_elastic_net10fold:
  methods:
    exec: naive.elasticnet.cv.wrapper.R
    Mytune: 10

lasso10fold_glmnet:
  methods:
    exec: lasso.glmnet.wrapper.R
    Mytune: 10

elastic_net10fold_glmnet:
  methods:
    exec: elasticnet.glmnet.wrapper.R
    Mytune: 10

ridge10fold:
  methods:
    exec: ridge.wrapper.R
    Mytune: 10
```
