### ISSUE TITLE
DSC terminology

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc2#68]
This page has to be re-defined (and everywhere in documentation and code ...):

https://stephenslab.github.io/dsc-wiki/doc/documentation/Terminology.html

**Comment by jdblischak** [comment]
Since we are trying to agree on terminology, it may be helpful to have another meeting where we try to agree on some terms. It's difficult to discuss terminology without a defined terminlogy :-)

**Comment by gaow** [comment]
@stephens999 comments here: 

https://github.com/stephenslab/dsc-wiki/blob/master/development/initial_thoughts_on_terminology_and_extraction.md

My first thoughts after reading through it is that we might have to think whether or not YAML based syntax has to be changed. I think most, if not all, features required in this document is already available under the current framework, but with perhaps counter-intuitive terminology and complicated syntax. On the other hand I do not think making the syntax entirely R-like is good because even if I write something that mimics and R parser, it is not R interpreter -- but users might think otherwise and therefore try / demand unreasonable stuff. 

Currently DSC operates in 3 steps: execute, apply tags and extract results. Or 2 steps if tags are added via automatic annotation. I started from YAML-like syntax because I think its simplicity is beyond compare and I tried to code DSC logic under this syntax. Generally I do not feel very much constrained though it does look a bit ugly in complicated cases -- mostly because it cannot be a one liner! If we are talking about re-designing syntax we should make sure the re-design is not only easier to specify DSC but also easier to extract from DSC. Or a balance between these.

The output data-frame part particularly needs more careful design. A way to go is perhaps write that part truly in R that takes input from DSC extracted data. The extracted data is basically a list of output from desired modules, of whatever return type. From here on it should be easy to entirely rely on R to operate on it. It's also more modular.

**Comment by stephens999** [comment]
thanks @gaow .
I don't think YAML syntax will need to be changed much. But I wanted to first start by 
making sure we are agreed on the main concepts, and a common terminology, and what
we would want to be able to extract. Then we can return to the YAML syntax.

My vision and hope
is that we should be able to develop a 2 step procedure (1. run pipelines; 2. extract results for plotting etc) that will work in most cases. If necessary we could add 
an additional annotation step between these two steps for edge cases (but I'm not yet convinced
it will be necessary).

I also believe that using YAML for the first step and R for the second step is an attractive initial goal.
It could be useful down the line to develop other interfaces for the second step (eg python etc).
But one thing at a time!

For now i want to check 
i) do you have suggested changes to terminology?
ii) are there any errors or misunderstandings in my text? 
iii) do you have other types of data extraction you think we should be considering that I did not mention here?

**Comment by gaow** [comment]
Thank you @stephens999 

> do you have suggested changes to terminology?

Instead of proposing chance let me try to merge your suggestion here with @jdblischak suggestion in #69 . From what you've described the concept of `module` sounds like a replacement to `step` in my old terms. My old `step` can take many parameter combinations, ie, many modules in your terms. The upside is its simplicity to easily try out various parameter combinations. The downside is the need of annotations later if only one set of combinations is required. In fact the same logic holds for the use of `block`, a simple way to organize many steps and compose pipeline. But if we do give up the succinctness of `step` we might well also give up the same property with `block` so that we remove the need of complicated annotations. Then we can replace `block` with the term `class` that @jdblischak proposes. For example the old syntax:

```
block_name:
   exec: SFA.R
   seed: 1, 2
   params:
     K: 10, 50
     tmp_file: File(sfa)
```

The new  (YAML-like) syntax:

```
class_name:
   seed: 1, 2 
   SFA_1:
     exec: SFA.R
     K: 10
     tmp_file: File(sfa)
   SFA_2(SFA_1):
     K: 20
  return: ...
```
And the pipeline will be defined by chains of logic operations on classes.

The `super class` concept that @jdblischak suggested is, to me, just an alias or short cut that helps with `DSC::run` syntax that we can certainly easily implement:

```
super_class: class_1 * (class_2, class_3)
```

Here `module` restricts choice of parameters to only one set and there is no long the concept of `step`. Because the same `module` can have many seeds then `task` would refer to each replicate of a `module`. 

From the engineering point of view, one parameter-set per module makes DSC much less efficient ... but that's a problem that I should face.

> are there any errors or misunderstandings in my text?

Conceptually no as I take the syntax you suggested are only conceptual. But you said "with exception of "multi-modules" (see later)." which I did not find elsewhere. multi-modules is essentially the old step design, ie, multiple parameter combinations per exec, right? I find it is hard to keep both multi-module and module concepts because multi-module will surely require annotation tags to track it.

> do you have other types of data extraction you think we should be considering that I did not mention here?

Dataframe sounds quite reasonable. Also if we can make dataframes then it makes it very easy to use Python on it as there is a package for Python interface to R dataframe (Hadley wrote the R part; my interface is more general yet less efficient). I'm not very much worried about formatting extracted data for now, though, because whatever final output we need will be extracted from a well-defined R list in a single RDS file as a result of `dsc -e`, so it'd be a pure R data manipulation problem which I believe R experts in the lab can give great suggestions. The harder part is how to extract data using as little (or no) annotation as possible. This goes back to question i) the terminology and syntax redesign. 

To sum up, to my understanding we use `superclass/class/module` model to replace `block/step` model. Certainly `module` will retire the use of annotation. But apparently where there are many exec and parameter combinations the new syntax lacks succinctness. For example the old syntax below would yield very long text in the new design proposed in this comment:

```
block_name:
  exec: 1.R, 2.R, 3.R, 4.R, 5.R
  params:
     K: 1, 2, 4, 50, 100, 200, 300
```

**Comment by stephens999** [comment]
sorry, @gaow  have not read the above yet, but I *have* just modified/added some things to my previous document.

**Comment by gaow** [comment]
Thank you @stephens999 . I read your updates. I think it's nice and clear. We are mostly settled on terminology, if you can comment on the idea of `super-module` or `sub-pipeline`

```
super_module: module_1 * (module_2, module_3)
```
Or 
```
sub_pipeline: module_1 * (module_2, module_3)
```

I personally prefer `super-module`. Another big issue is that I need comments on the loss of succinctness  as a consequence of removing the block/step concept for cases such as the following (also see thread above). 

```
block_name:
  exec: 1.R, 2.R, 3.R, 4.R, 5.R
  params:
     K: 1, 2, 4, 50, 100, 200, 300
```

Seed issue and extracting info should go to separate tickets that I'm about to create.

**Comment by gaow** [comment]
Here is a elaborated example. With the current interface:

```
method_series_1:
  exec: 1.R, 2.R, 3.R, 4.R, 5.R
  params:
     K: 1, 2, 4, 50, 100, 200, 300
  return: something

method_series_2:
  exec: 1.R, 2.R, 3.R, 4.R, 5.R
  params:
     gamma: 0.1, 0.2, 0.4, 5, 10, 20, 30
  return: something

DSC:
   run: 
     pipeline_1: one_block * another_block * (method_series_1, method_series_2) * final_block 
     pipeline_2: ...
```

With proposed syntax that replaces the concept of block with modules and no multiple steps in the same module:

```
method_series_1:
  exec: 1.R
  params:
     K: 1
  return: something

method_series_2(method_series_1):
  exec: 2.R
  params:
    K: 1

(and you'll have 35 modules for K related parameters and another 35 modules for gamma related parameters).

DSC
   run:
    pipeline_1:   one_block * another_block * method_series_1 * final_block 
    pipeline_2: ...

(you'll have to write 70 pipelines)
```
