### ISSUE TITLE
Force DSC input executables to provide a "main" function call

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc2#74]
This issue is separated from #73 . It is easy to understand DSC module as calling a function defined in a script. What DSC does is to specify variables (input, parameters , output) to interact with the function call. For example the R script `mean.R` can have 2 versions:

### version 1
```r
get_mean = function(x) {
  median(x)
}
output = get_mean(sample_data)
```
### version 2

```r
output = median(sample_data)
```
and the DSC below will work on either version

```yaml
median: mean.R
   params:
     sample_data: $X
   return: output
```

However if we do force the script to wrap everything as a main function, ie. version 1 exclusively, then we can perhaps slightly change the DSC syntax to:
```r
get_mean = function(x) {
  median(x)
}
```
and
```yaml
median: mean.R
   params:
     sample_data: $X
   return: output = get_mean(sample_data)
```
Down-sides:

1. It's a bit restrictive because it no longer allows loose lines of codes. (this may also be an upside because it is arguably good practice to always use functions?) In Python loose codes is somewhat more acceptable if I write:

```python
if __name__ == '__main__':
    x = 1
    save(...)
```

instead of just 

```python
x = 1
save()
```

2. For object oriented programming there may not be a `function` call but a series of `class.method()` calls which cannot be made available via a single line of return in DSC file

3. Most importantly is executables. For example (code not tested but this is how DSC works):

```
sfa: sfa -o $output -k $K ...
  params:
    output: File(sfa)
    K: 10
  return: output
```
So there is no function call involived.
