### ISSUE TITLE
Explicitly specify pipeline input / output

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc2#76]
Suggested by @stephens999 : 

Another issue that may be not urgent, but has been on my mind for a while, so I want to mention it now, just in case.

I think it might be useful to allow (encourage?) users to specify which pipeline variables are input and output to each group, as a kind of “double-check” that everything is as expected.

```
# Specify pipeline variabels -strictly not necessary as they are specified
# implicitly in the modules, but helpful for logic, and for checking/avoiding mistakes?

SIMULATE:
  input: NULL
  output: $x, $truemean

ESTIMATE:
  input: $x
  output: $estmean

SCORE:
  input: $estmean, $truemean
  output: $score`

```
the above woudl be the kind of thing I had in mind…

the idea would be that if someone added a new module to the SCORE group, then they would know it has to take input $estmean and $truemean and output $score. And dsc could check that it does that.

I think this kind of thing could all be downstream of our current discussion as this is essentially redundant information not actually necessary to run a dsc… so I am happy to defer discussion of it to later when we have other things set. But I’m mentioning it now just in case you think it impacts any decisions we would make now.
