### ISSUE TITLE
File() operator in DSC

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc2#80]
Currently each DSC module will generate an output, which, by default, an RDS file object that stores `output` pipeline variables. The name for the RDS file is automatically determined by DSC that ensures uniqueness with respect to a pipeline instance. 

However particularly for commandline-based `exec` we may want to keep track of other files it generates. The syntax is now:

```
cmd:
   exec: echo $seed 1> $dest 2> $error
   input:
     seed: R(1:5)
     dest: File(out)
     error: File(err)
   output:
     $cmd_output: dest
```
Then DSC will run 5 times, each time writing a seed value to a file called `xxx.out` where `xxx` is a prefix automatically determined by DSC, like it does it for RDS files, and the extension `out` is specified along with `File()`.

Because `output` asks for `dest`, we will store `dest` in the output directory and we keep track of this file. Otherwise as with the case of `error` we'll generate `xxx.err` but we do not keep track of it.

In another occasion when `File()` takes no suffix, DSC will only take the `xxx` part of it. It is indeed still a valid file name, only without an extension. This can be conveniently used as a unique identifier of the outcome of a particular pipeline instance. 

For another example:

```
sfa_pre:
 exec: R(write.table(input, file=sfain, row.names=F, col.names=F)
 input:
   input: @Xtrain
   sfain: File(.sfa)
 output:
   @sfain: sfain

sfa_run:
   exec: SFAmix  --nf $K --y $sfain --out $sfout  --sep space > $log
   input:
     K: 2
     sfain: @sfain
     sfaout: File(.sfa)
     log: File(.log)
   output:
     @sfaout: sfaout

sfa_post:
  exec: sfa_postprocessing.R
  input: 
    sfaout: @sfaout
 output:
   @Omega: Omega
 

DSC:
  define: 
    sfa: sfa_pre * sfa_run * sfa_post
  run: data * sfa * score
  clean: sfa_pre, sfa_run, !score
  purge: data
```
