### ISSUE TITLE
Syntax for module specific parameters

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc2#82]
It was previously documented here:

https://stephenslab.github.io/dsc-wiki/doc/documentation/DSC_Configuration.html#exec-specific-parameters

But we may want to change it:

1. We do not like `exec[?]`. Should we use `module[?]` or just `[?]`.
2. `?` could be an index eg `module[1]`, or a key eg `module[SFA]`. We may want to keep only one of it. I'd vote for key based (`module[SFA]`). It is safer because order of modules would no longer matter.

**Comment by stephens999** [comment]
For 2, I agree, use module key.

For 1, I prefer just [?] to module[?]. 

I think it is useful to have a link to this example:
https://github.com/stephenslab/dsc2-omega/blob/master/dsc2/omega.dsc

Peter asked if you need [] - could just not allow the user to use variables with same
names as module... but this is clearly a bit more restrictive.

Peter also asked at what level you can use this in the module definition -
can it be at any level (e.g. before `input`) or only at the top level?

And, how flexible is the intended use? Eg
can you use `[glasso1,glasso2]: ` if two modules share the same parameter value?
 
Another possibility, we may have discussed at our meeting(?):

`glasso1.rho: xx
glasso2.rho: yy`

**Comment by gaow** [comment]
> I think it is useful to have a link to this example

We have a dedicated page to list examples: https://stephenslab.github.io/dsc-wiki/examples.html

But I'll use some of these examples as I update the documentation

> Peter asked if you need []

Being restrictive makes the syntax more clear though I'm not even sure if YAML likes `[]` there. Without `[]` is already reserved for grouped parameters:

https://stephenslab.github.io/dsc-wiki/doc/documentation/DSC_Configuration.html#Grouped-parameters

> can you use [glasso1,glasso2]: if two modules share the same parameter value?

Yes

> glasso1.rho: xx glasso2.rho: yy

We did discuss this, but decide it would be ugly when complicated:

```
glasso1.a: xx 
glasso1.b: yy
glasso1.c: zz
...
```

Also R users would like to think dotted variable just a varible, not indicating a namespace or a member of something. So we think it is perhaps better to make it explicit with `[]`

**Comment by pcarbo** [comment]
> Without [] is already reserved for grouped parameters:

I think Matthew's point is that if the name is already defined as a module, then you could automatically interpret it as an exec-specific parameter. So it doesn't seem like the square brackets are strictly necessary, unless you would want both grouped parameters and exec-specific parameters that have the same name:

```
[glasso1]:
  rho: (0.05, 0.8)
glasso1:
  n: 4
```

But that doesn't seem like a good idea!

Some other examples of this sort of syntax, building on your [previous example](https://github.com/stephenslab/dsc2-omega/blob/master/dsc2/omega.dsc). Which are valid, and which are not?

A. Here I'm just pasting your original example:

```
glasso1:
  rho: (0.05, 0.8)
glasso2:
  rho: (0.01, 0.05)
glasso3:
  rho: (0.4, 0.9)
```

B. Here I have a "default" value for `rho` that is overidden in `glasso1` only:

```
rho: (0.4, 0.9)
glasso1:
  rho: (0.05, 0.8)  
```

C. Here `glasso2` and `glasso3` have the same `rho` (I think you have already answered this question, but just double-checking):

```
glasso1:
  rho: (0.05, 0.8)
glasso2, glasso3:
  rho: (0.01, 0.05)
```

D. Here we define values of `rho` for all three modules, but in a different order:

```
glasso3:
  rho: (0.4, 0.9)
glasso2:
  rho: (0.01, 0.05)
glasso1:
  rho: (0.05, 0.8)
```

E. Here we define multiple variables for each module:

```
glasso1:
  rho: (0.05, 0.8)
  K: 20
glasso2:
  rho: (0.01, 0.05)
  K: 20
glasso3:
  rho: (0.4, 0.9)
  K: 10
```

F. Here `rho` is not specified within a contiguous block:

```
glasso1:
  rho: (0.05, 0.8)
glasso2:
  rho: (0.01, 0.05)
K: 20
n: 5
glasso3:
  rho: (0.4, 0.9)
```

G. Can this syntax be used other than the `input` block? e.g., `output`?

**Comment by gaow** [comment]
## Grouped parameter vs []

Ok if we do allow for exec specific parameter without `[]` and allow for grouped parameter at the same time, we'll end up:

```
glasso1, glasso2:
  exec: glasso.R
  input:
    tuning:
     rho: (0.05, 0.8)
   glasso1:
     rho: (0.1, 0.5)
```
It will look a bit confusing between grouped parameters and exec specific parameters. Again grouped parameter is just an eye candy. I find it helps organizing DSC script and enhance readiblity. But if we confuse it with exec specific parameter we it may defeat the point.  

All your syntax A to F are valid. It is just a question of whether we are comfortable mixing exec-specific with grouped parameter syntax conventions. From the point of parsing it would not be difficult. You can possibly argue that `glasso1` is also a type of argument groups. But here group name matters, vs in the grouped variable design it does not. 

For G, the answer is yes but limited. The first level only supports `exec`, `input` and `output`. Inside `output` we'll allow for this case:

https://github.com/stephenslab/dsc2-omega/blob/master/dsc2/omega.dsc#L101

(ignore the obsolete syntax). But DSC will do quit on error if different exec output are not the same, because it would otherwise logically dangerous. Can you think of a counter argument?
